- name: Remove ntp package
  apt: name=ntp state=absent

- name: Ensure chrony package is installed
  apt: name=chrony state=present

- name: Install chrony.conf
  template: src=chrony.conf dest=/etc/chrony/chrony.conf owner=root group=root mode=0644
  notify: Restart chrony

- name: Ensure chrony is started and enabled
  service: name=chrony state=started enabled=yes
